FROM openjdk:22-jdk-slim
RUN apt-get update \
    && apt-get install -y iputils-ping netcat-traditional wget gettext curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]