FROM openjdk:22-jdk-slim
RUN apt-get update \
    && apt-get install -y iputils-ping netcat-traditional wget gettext curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY . .
RUN ./mvnw clean install
# development/debug mode at 5005
CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.jvmArguments=\"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005\""]