kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.30.2
    # https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts
    extraPortMappings:
    - containerPort: 32000
      hostPort: 32000
      protocol: TCP
    - containerPort: 32005
      hostPort: 32005
      protocol: TCP
    - containerPort: 32555
      hostPort: 32555
      protocol: TCP
  - role: worker
    image: kindest/node:v1.30.2
    extraMounts:
      - hostPath: /home/adrian/repos/SpringHello/src/main/java/
        containerPath: /mnt/app/src/main/java/
  - role: worker
    image: kindest/node:v1.30.2
    extraMounts:
      - hostPath: /home/adrian/repos/SpringHello/src/main/java/
        containerPath: /mnt/app/src/main/java/
  - role: worker
    image: kindest/node:v1.30.2
    extraMounts:
      - hostPath: /home/adrian/repos/SpringHello/src/main/java/
        containerPath: /mnt/app/src/main/java/
# containerdConfigPatches:
#   - |-
#     [plugins."io.containerd.grpc.v1.cri".registry.configs."local.registry.com".tls]
#       cert_file = "/etc/docker/certs.d/local.registry.com/local.registry.com.crt"
#       key_file  = "/etc/docker/certs.d/local.registry.com/local.registry.com.key"